config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "pages#home"
  # verb "path", to: "controller#action"
  get "restaurants", to: "restaurants#index"
  get "restaurants/new", to: "restaurants#new", as: :new_restaurant
  post "restaurants", to: "restaurants#create"
  get "restaurants/:id", to: "restaurants#show", as: :restaurant
  get "restaurants/:id/edit", to: "restaurants#edit", as: :edit_restaurant
  patch "restaurants/:id", to: "restaurants#update"
  delete "restaurants/:id", to: "restaurants#destroy"

  resources :restaurants do
    resources :bookings, except: [:destroy]
    delete "bookings/:id", to: "bookings#destroy", as: :delete_booking
    resources :reviews, only: [:new, :create]
  end

  resources :bookings, only: %i[index]

  resources :reviews, only: %i[destroy]
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

  validates :date, presence: true
  validates :user_id, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[edit update destroy]
  before_action :set_restaurant, only: %i[new create]

  def index
    @bookings = current_user.bookings.order(date: :asc)
  end

  def new
    @booking = Booking.new(restaurant: @restaurant)
  end

  def create
    @booking = @restaurant.bookings.new(booking_params)
    @booking.user = current_user


    if @booking.save
      redirect_to bookings_path
    else
      puts @booking.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @restaurant = @booking.restaurant
  end

  def update
    if @booking.update(booking_params)
      redirect_to bookings_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def booking_params
    params.require(:booking).permit(:restaurant_id, :date)
  end
end

app/views/bookings/_form.html.erb
<div class="booking-container">
    <%= simple_form_for [@restaurant, @booking] do |f| %>
      <div id="booking-form">
        <%= f.input :date, as: :datetime, order: [:day, :month, :year], label_html: {class: 'label-text'} %>
        <%= f.submit %>
      </div>
    <% end %>
  </div>

app/views/bookings/edit.html.erb
<div class="edit-booking-container">
  <div class="edit-booking-card">
    <h2 id="edit-booking-title">Edit Booking of <%= @restaurant.name %> restaurant</h2>
    <%= render "form", booking: @booking %>
    <%= link_to 'Back', bookings_path %>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="bookings-container">
  <div id="bookings">
    <h4 id="h4-title"> Welcome <strong><%= current_user.first_name.capitalize %></strong> to your
      <%= "booking#{ 's' if @bookings.count > 1 }" %>
    </h4>
      <div id="booking-list">
        <% if @bookings.present? %>
            <% @bookings.each do |booking| %>
              <li>
                <%= link_to restaurant_path(booking.restaurant) do %>
                  <%= booking.restaurant.name %>
                <% end %>
                <%= booking.date.strftime("%e %b %Y %H:%M") %>

              </li>
              <div class="btn-back">
                <%= link_to "Back", restaurants_path %>
                <%= link_to "Edit", edit_restaurant_booking_path(booking.restaurant, booking) %>
                <%= link_to "Cancel Booking", restaurant_delete_booking_path(booking.restaurant, booking), class: "cancel-btn",
                    data: {turbo_method: :delete, turbo_confirm:
                    "Cancel booking for #{booking.restaurant.name} restaurant at #{booking.date.strftime("%e %b %Y %H:%M")}?"} %>
              </div>
            <% end %>
          <% else %>
            <h2>You have not booked a table yet?</h2>
        <% end %>

      </div>
  </div>
</div>

app/views/bookings/new.html.erb
<%= render "form", booking: @booking %>