config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "pages#home"
  # verb "path", to: "controller#action"
  get "restaurants", to: "restaurants#index"
  get "restaurants/new", to: "restaurants#new", as: :new_restaurant
  post "restaurants", to: "restaurants#create"
  get "restaurants/:id", to: "restaurants#show", as: :restaurant
  get "restaurants/:id/edit", to: "restaurants#edit", as: :edit_restaurant
  patch "restaurants/:id", to: "restaurants#update"
  delete "restaurants/:id", to: "restaurants#destroy"

  resources :restaurants do
    resources :bookings, except: [:destroy]
    delete "bookings/:id", to: "bookings#destroy", as: :delete_booking
    resources :reviews, only: [:new, :create]
  end

  resources :bookings, only: %i[index]

  resources :reviews, only: %i[destroy]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-mrst">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "RT_logo.png", id: "logo-img" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-home active">
            <%= link_to "Home", root_path , class: "nav-link" %>
          </li>
          <li class="nav-restaurants">
            <%= link_to "Restaurants", restaurants_path, class: "nav-link" %>
          </li>
            <% if @bookings.nil? %>
              <li class="nav-bookings">
                <%= link_to "My Bookings", bookings_path, class: "nav-link" %>
              </li>
            <% end %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.avatar.attached? %>
              <%= image_tag current_user.avatar, class: "avatar", alt: "dropdown menu" %>
            <% else %>
              <%= image_tag "avatar_default.png", class: "avatar", alt: "dropdown menu" %>
            <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "User", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-login">
            <%= link_to "Login", new_user_session_path, class: "nav-link", data: { turbo_frame: "modal" } %>
          </li>

        <% end %>
      </ul>
    </div>
  </div>
</div>