config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: "pages#home"
  # verb "path", to: "controller#action"
  get "restaurants", to: "restaurants#index"
  get "restaurants/new", to: "restaurants#new", as: :new_restaurant
  post "restaurants", to: "restaurants#create"
  get "restaurants/:id", to: "restaurants#show", as: :restaurant
  get "restaurants/:id/edit", to: "restaurants#edit", as: :edit_restaurant
  patch "restaurants/:id", to: "restaurants#update"
  delete "restaurants/:id", to: "restaurants#destroy"

  resources :restaurants do
    resources :bookings, except: [:destroy]
    delete "bookings/:id", to: "bookings#destroy", as: :delete_booking
    resources :reviews, only: [:new, :create]
  end

  resources :bookings, only: %i[index]

  resources :reviews, only: %i[destroy]
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :users

  validates :name, :address, :city, :postal_code, presence: true
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]

  def index
    @restaurants = Restaurant.all

    # unless @restaurants = nil
      query = [:queryname, :querycity, :queryaddress]
      if query.any? { |attribute| params[attribute].present? }
        query.each do |attribute|
          if params[attribute].present?
            column_name = attribute.to_s.gsub('query', '').to_sym
            @restaurants = @restaurants.where("#{column_name} ILIKE ?", "%#{params[attribute]}%")
          end
        end
      end
    # end

  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  def show
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path, status: :see_other
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :city, :postal_code, :rating)
  end
end

app/views/restaurants/_form.html.erb
<div class="simple-form p-5">
  <%= simple_form_for(restaurant) do |f| %>
    <%= f.input :name, label_html: {class: 'name-text'} %>
    <%= f.input :address, label_html: {class: 'address-text'} %>
    <%= f.input :city, label_html: {class: 'city-text'} %>
    <%= f.input :postal_code, label_html: {class: 'postal-code-text'} %>
    <%= f.input :rating, collection: 1..5, as: :radio_buttons %>
    <%= f.submit %>
  <% end %>

  <%= link_to "Back", :back %>
</div>

app/views/restaurants/edit.html.erb
<div class="edit-restaurant-container">
  <div class="edit-restaurant-card">
    <h2 id="edit-restaurant-title">Edit <%= @restaurant.name %></h2>

    <%= render "form", restaurant: @restaurant %>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="restaurants-container">
  <ul>
    <% if @restaurants.present? %>
      <% @restaurants.each do |restaurant| %>
        <li>
          <div class="restaurant-card">
            <%= link_to restaurant.name, restaurant_path(restaurant) %>
          </div>
        </li>
      <% end %>
    <% else %>
      <h2>Restaurant not found!</h2>
    <% end %>
  </ul>
  <div class="btn-create">
    <%= link_to "Create a Restoraurant",  new_restaurant_path %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h2>Create new restaurant</h2>

  <%= render "form", restaurant: @restaurant %>
</div>

app/views/restaurants/show.html.erb
<div class="bg-img" style="background-image: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.5)),
            url(<%= asset_path('top-view-food-banquet_resized.jpg')%>)">
</div>

<div class="restaurant">
  <h2 id="restaurant-name"><%= @restaurant.name %>'s Restaurant </h2>
  <p id="restaurant-address">Address: <%= @restaurant.address %></p>
  <p id="restaurant-city">City: <%= @restaurant.city %></p>
  <p id="restaurant-postal-code">Postal Code: <%= @restaurant.postal_code %></p>
  <p id="restaurant-rating">Rating: <%= @restaurant.rating %></p>
  <p id="restaurant-reviews"><strong>Reviews</strong></p>
  <ul class="reviews">
    <% @restaurant.reviews.each do |review| %>
      <li class="review-item">
        <%= review.content %>
        <%= link_to "Delete", review_path(review),
            data: {turbo_method: :delete, turbo_confirm: "Delete this review?"} %>
      </li>
    <% end %>
  </ul>
  <br>
  <div class="restaurant-buttons">
      <%= link_to "Back", :back %>
      <%= link_to "Edit", edit_restaurant_path %>
      <%= link_to "Add Review", new_restaurant_review_path(@restaurant) %>
      <%= link_to "Delete", restaurant_path(@restaurant),
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      <%= link_to "Restaurants", restaurants_path %>
      <%= link_to "Book a table", new_restaurant_booking_path(restaurant_id: @restaurant.id) %>
  </div>
</div>